/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import DBscan.DBScan;
import DBscan.Tuple;
import gridgrowing.GridClustering;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author AdamGu0
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();

        rd = new ReadData();

        clusterPanel = new ClusterPanel(rd);
        tabbedViewerPanel.addTab("2D", clusterPanel);
        mapKit = new MapKit();
        tabbedViewerPanel.addTab("GPS", mapKit);

        // for Grid-Based Clustering
        mapKit.getMainMap().addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                if (mapKit.gridBased.doGridBasedClustering()) {
                    showResultInfo(mapKit.gridBased.clustersArray, mapKit.gridBased.duration, "Grid-Based");
                }
            }
        });
        mapKit.getMainMap().addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            @Override
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                if (mapKit.gridBased.doGridBasedClustering()) {
                    showResultInfo(mapKit.gridBased.clustersArray, mapKit.gridBased.duration, "Grid-Based");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        settingPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minPtsTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        epsTextField = new javax.swing.JTextField();
        dbscanButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kMeansTextField = new javax.swing.JTextField();
        iterationsTextField = new javax.swing.JTextField();
        kMeansButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        smartSwapTextField = new javax.swing.JTextField();
        smartSwapButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        mTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        optionComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        nxTextField = new javax.swing.JTextField();
        nyTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gridGrowingButton = new javax.swing.JButton();
        gridBasedPanel = new javax.swing.JPanel();
        gridBasedButton = new javax.swing.JButton();
        gridSizeSlider = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        gridSizeLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        tabbedViewerPanel = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        dimensionsLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dataTypeLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        clustersLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mseLabel = new javax.swing.JLabel();
        chLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        algorithmLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        normalDataMenuItem = new javax.swing.JMenuItem();
        gpsDataMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geo-Cluster");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DBScan Clustering"));
        jPanel1.setToolTipText("");

        jLabel1.setText("MinPts");

        minPtsTextField.setText("17");

        jLabel2.setText("eps");

        epsTextField.setText("22000");

        dbscanButton.setText("run");
        dbscanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbscanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minPtsTextField)
                            .addComponent(epsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dbscanButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(minPtsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(epsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbscanButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("K-Means Clustering"));

        jLabel3.setText("K");

        jLabel4.setText("Iterations");

        kMeansTextField.setText("15");

        iterationsTextField.setText("100");

        kMeansButton.setText("run");
        kMeansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kMeansButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kMeansTextField)
                            .addComponent(iterationsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kMeansButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kMeansTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(iterationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kMeansButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("SmartSwap Clustering"));

        jLabel5.setText("K");

        smartSwapTextField.setText("10");

        smartSwapButton.setText("run");
        smartSwapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smartSwapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smartSwapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(smartSwapButton))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(smartSwapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smartSwapButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("GridGrowing Clustering"));

        jLabel6.setText("M");

        mTextField.setText("31");

        jLabel7.setText("Seed");

        optionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "random", "max values", "aliquot" }));

        jLabel8.setText("Nx");

        nxTextField.setText("147");

        nyTextField.setText("146");

        jLabel9.setText("Ny");

        gridGrowingButton.setText("run");
        gridGrowingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridGrowingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optionComboBox, 0, 1, Short.MAX_VALUE)
                            .addComponent(mTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gridGrowingButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridGrowingButton))
        );

        gridBasedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Grid-Based Clustering"));

        gridBasedButton.setText("run");
        gridBasedButton.setEnabled(false);
        gridBasedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBasedButtonActionPerformed(evt);
            }
        });

        gridSizeSlider.setMinimum(30);
        gridSizeSlider.setValue(60);

        jLabel19.setText("Grid Size:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gridSizeSlider, org.jdesktop.beansbinding.ELProperty.create("${value}"), gridSizeLabel, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout gridBasedPanelLayout = new javax.swing.GroupLayout(gridBasedPanel);
        gridBasedPanel.setLayout(gridBasedPanelLayout);
        gridBasedPanelLayout.setHorizontalGroup(
            gridBasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gridBasedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gridBasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gridBasedButton)
                    .addGroup(gridBasedPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gridSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(gridSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        gridBasedPanelLayout.setVerticalGroup(
            gridBasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gridBasedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gridBasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(gridSizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridBasedButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gridBasedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridBasedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        stateLabel.setText(" ");

        tabbedViewerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel5.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        jLabel10.setText("Data File:");

        fileTextField.setEditable(false);
        fileTextField.setText("Please open a data file.");

        dimensionsLabel.setText("N/A");

        jLabel12.setText("Dimensions:");

        pointsLabel.setText("N/A");

        jLabel11.setText("Points:");

        jLabel18.setText("Data type:");

        dataTypeLabel.setText("N/A");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(pointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dimensionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fileTextField))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pointsLabel)
                    .addComponent(jLabel12)
                    .addComponent(dimensionsLabel)
                    .addComponent(jLabel18)
                    .addComponent(dataTypeLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        logTextArea.setEditable(false);
        logTextArea.setColumns(23);
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        jLabel13.setText("Output:");

        jLabel14.setText("Clusters:");

        clustersLabel.setText("N/A");

        jLabel15.setText("MSE:");

        jLabel16.setText("CH:");

        jLabel17.setText("Time:");

        mseLabel.setText("N/A");
        mseLabel.setMaximumSize(new java.awt.Dimension(160, 16));

        chLabel.setText("N/A");

        timeLabel.setText("N/A");

        jLabel20.setText("Algorithm:");

        algorithmLabel.setText("N/A");

        saveButton.setText("save");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clustersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(mseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(algorithmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(algorithmLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(clustersLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(mseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(chLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(timeLabel))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedViewerPanel.addTab("Log", jPanel5);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        normalDataMenuItem.setMnemonic('o');
        normalDataMenuItem.setText("Open normal data");
        normalDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalDataMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(normalDataMenuItem);

        gpsDataMenuItem.setMnemonic('s');
        gpsDataMenuItem.setText("Open GPS data");
        gpsDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpsDataMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(gpsDataMenuItem);

        saveMenuItem.setMnemonic('a');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedViewerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabbedViewerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedViewerPanel.getAccessibleContext().setAccessibleName("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void dbscanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbscanButtonActionPerformed
        mapKit.gridBased.startGridBased = false;
        doDBScan();
    }//GEN-LAST:event_dbscanButtonActionPerformed

    private void kMeansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kMeansButtonActionPerformed
        mapKit.gridBased.startGridBased = false;
        doKMeans();
    }//GEN-LAST:event_kMeansButtonActionPerformed

    private void smartSwapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smartSwapButtonActionPerformed
        mapKit.gridBased.startGridBased = false;
        doSmartSwap();
    }//GEN-LAST:event_smartSwapButtonActionPerformed

    private void gridGrowingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridGrowingButtonActionPerformed
        mapKit.gridBased.startGridBased = false;
        doGridGrowing();
    }//GEN-LAST:event_gridGrowingButtonActionPerformed

    private void gridBasedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBasedButtonActionPerformed
        switch (mapKit.gridBased.startGridBasedClustering(data, gridSizeSlider.getValue())) {
            case 0:
                this.tabbedViewerPanel.setSelectedIndex(2);
                showResultInfo(mapKit.gridBased.clustersArray, mapKit.gridBased.duration, "Grid-Based");
                break;
            case 1:
                showWarning("There is no data of points");
                break;
            case 2:
                showWarning("There is no point!");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_gridBasedButtonActionPerformed

    private void normalDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalDataMenuItemActionPerformed
        loadFile(false);
    }//GEN-LAST:event_normalDataMenuItemActionPerformed

    private void gpsDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpsDataMenuItemActionPerformed
        loadFile(true);
    }//GEN-LAST:event_gpsDataMenuItemActionPerformed

    public void setIsGPSData(boolean isGPSData) {
        if (isGPSData) {
            dataTypeLabel.setText("GPS");
        } else {
            dataTypeLabel.setText("Normal");
        }
        this.isGPSData = isGPSData;
        gridBasedButton.setEnabled(isGPSData);
    }

    public void showResultInfo(Cluster[] clusters, long duration, String algorithm) {
        this.algorithm = algorithm;
        String a = algorithm + " Clustering";
        
        int length = clusters.length;
        String str = "Algorithm: " + a + "\n\nThere are " + length + " clusters.\nCenters:\n";
        for (int i = 0; i < length; i++) {
            str += (i + 1) + ". " + clusters[i].centroid.toString() + "\n";
        }
        
        //get the mse
        double ssdAll = 0;
        for (Cluster c : clusters) {
            ssdAll += c.calcSsd();
        }
        double mse = ssdAll / data.length;
        
        //get the CH
        double ch = 0;
        if (length > 1) {
            double SSB = ClusterData.calcSSB(clusters, rd.isGPSData);
            if (length != 1) {
                ch = (SSB / (length - 1)) / mse; //why -1?
            }
        }
        
        algorithmLabel.setText(a);
        clustersLabel.setText(String.valueOf(length));
        mseLabel.setText(String.valueOf(mse));
        chLabel.setText(String.valueOf(ch));
        timeLabel.setText(String.valueOf(duration) + "ms");
        stateLabel.setText("Clusters:" + length + " MSE:" + mse + " CH:" + ch + " Time:" + duration + "ms");
        logTextArea.setText(str + "\nMSE:" + mse + "\nCH:" + ch + "\nTime:" + duration + "ms\n");
    }

    private void loadFile(boolean isGPSData) {
        FileFilter filter;
        filter = new FileFilter() {
            @Override
            public boolean accept(File f) {
                return (f.isDirectory()
                        || f.getPath().toLowerCase().endsWith(".txt")
                        || f.getPath().toLowerCase().endsWith(".csv"));
            }

            @Override
            public String getDescription() {
                return "Data files(*.txt, *.csv)";
            }
        };
        JFileChooser file = new JFileChooser(".");
        file.addChoosableFileFilter(filter);
        int result = file.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            if (selectedFile != null) {
                File dataFile = selectedFile;

                if (rd.readData(dataFile, isGPSData)) // check the validity of data
                {
                    showWarning("");
                    data = rd.getPoints();
                    fileName = file.getSelectedFile().getName();
                    //this.setTitle(fileName);
                    fileTextField.setText(file.getSelectedFile().getAbsolutePath());
                    pointsLabel.setText(Integer.toString(data.length));
                    dimensionsLabel.setText(Integer.toString(rd.getVectorSize()));
                    setIsGPSData(isGPSData);
                } else {
                    showWarning("File is invalid!");
                }
            }
        }
    }

    private void doDBScan() {

        //check the input data and parameters
        if (data == null) {
            showWarning("There is no data of points");
            return;
        } else if (data.length == 0) {
            showWarning("There is no point!");
            return;
        }

        //int dimension = 0;
        //dimension = data[0].vectorSize;
        if (minPtsTextField.getText().equals("") || epsTextField.getText().equals("")) {
            showWarning("Please input the MinPts and Eps!");
            return;
        }
        //set the algorithm parameters
        DBScan.Eps = Double.parseDouble(epsTextField.getText());
        DBScan.MinPts = Integer.parseInt(minPtsTextField.getText());

        long startDBScan = System.currentTimeMillis();
        DBScan dbscanAlgorithm = new DBScan();
        List<Tuple> tuples = new ArrayList<Tuple>();
        for (Point data1 : data) {
            tuples.add(new Tuple(rd.isGPSData, data1.vectors[0], data1.vectors[1]));
        }
        dbscanAlgorithm.setDataObjectsAndBuildRTree(tuples);
        dbscanAlgorithm.checkCorePoints();
        int clusterNumber = dbscanAlgorithm.dbscan();
        long duration = System.currentTimeMillis() - startDBScan;

        //get the clusters to be shown according to the result of 'dbscanAlgorithm.dbscan()'
        Cluster[] clusters = new Cluster[clusterNumber];
        for (int i = 0; i < clusterNumber; i++) {
            clusters[i] = new Cluster(rd.isGPSData, data[0].vectors.length);
            //clusters[i].setVectorSize(data[0].vectorSize);  //actually, it is the dimension of data(2)
            clusters[i].setVectorSize(2);
            //TODO: how to calculate the centroid?????
            //clusters[i].calcCentroid(null);
        }
        //loop the dbscanAlgorithm.dataObjects to get the tuples
        //whose clusterID is i, then transfer it to point and add to 
        //the cluster
        Iterator<Tuple> iterator = dbscanAlgorithm.dataObjects.iterator();
        int count = 0;
        while (iterator.hasNext()) {
            count++;
            Tuple tuple = iterator.next();
            if (tuple.clusterID >= 1) {
                //System.out.println("clusterID: "+ tuple.clusterID);
                double[] d = new double[2];
                d[0] = tuple.xValue;
                d[1] = tuple.yValue;
                clusters[tuple.clusterID - 1].pointsList.add(new Point(d, rd.isGPSData));
            }
        }
        // not sure if it is correct to set the centroid this way
        for (int i = 0; i < clusterNumber; i++) {
            clusters[i].calcCentroid(new Point(rd.isGPSData));
        }

        showResultInfo(clusters, duration, "DBScan");
        showResult(clusters);

        //save the DBscan cluster point in json file, for drawing point on googlemap
        //saveCluster(preFileName+"_DBscan", clusters, clusters.length);
    }

    private void doKMeans() {
        if (data == null) {
            showWarning("There is no data of points");
            return;
        } else if (data.length == 0) {
            showWarning("There is no point!");
            return;
        }

        if (kMeansTextField.getText().equals("") || iterationsTextField.getText().equals("")) {
            showWarning("Please input the number of clusters and steps!");
            return;
        }

        if (data != null) {
            int k;  // number of clusters
            int kIterations; // iterations for kmeans
            long start, end, duration; // start, end and duration of clustering method
            k = Integer.parseInt(kMeansTextField.getText());
            kIterations = Integer.parseInt(iterationsTextField.getText());
            ClusterData cd = new ClusterData(data, rd.isGPSData);
            start = System.currentTimeMillis();
            Cluster[] clusters = cd.kmeans(k, kIterations);
            end = System.currentTimeMillis();
            duration = end - start;

            showResultInfo(clusters, duration, "K-Means");
            showResult(clusters);

            //save the Kmeans cluster point in json file, for drawing point on googlemap
            //saveCluster(preFileName+"_KMeans", clusters, clusters.length);
        } else {
            showWarning("There is no data of points");
        }
    }

    private void doSmartSwap() {
        if (data == null) {
            showWarning("There is no data of points");
            return;
        } else if (data.length == 0) {
            showWarning("There is no point!");
            return;
        }

        if (smartSwapTextField.getText().equals("")) {
            showWarning("Please input the number of cluster!");
            return;
        }

        if (data != null) {
            int k;  // number of clusters
            long start, end, duration; // start, end and duration of clustering method

            k = Integer.parseInt(smartSwapTextField.getText());
            ClusterData cd = new ClusterData(data, rd.isGPSData);
            start = System.currentTimeMillis();
            Cluster[] clusters = cd.smartSwap(k);
            end = System.currentTimeMillis();
            duration = end - start;
            
            showResultInfo(clusters, duration, "SmartSwap");
            showResult(clusters);

            //save the SmartSwap cluster point in json file, for drawing point on googlemap
            //saveCluster(preFileName+"_SmartSwap", clusters, clusters.length);    
        } else {
            showWarning("There is no data of points");
        }
    }

    public void doGridGrowing() {
        //check the input data and parameters
        if (data == null) {
            showWarning("There is no data of points");
            return;
        } else if (data.length == 0) {
            showWarning("There is no point!");
            return;
        }

        if (mTextField.getText().equals("") || nxTextField.getText().equals("") || nyTextField.getText().equals("")) {
            showWarning("Please input all the parameters!");
            return;
        }

        if (Integer.parseInt(mTextField.getText()) < 1) {
            showWarning("The parameter of M is wrong!");
            return;
        }

        //set the algorithm parameters
        int mParameter = Integer.parseInt(mTextField.getText());
        int optionParameter = optionComboBox.getSelectedIndex();
        int nxParameter = Integer.parseInt(nxTextField.getText());
        int nyParameter = Integer.parseInt(nyTextField.getText());

        long startTime = System.currentTimeMillis();
        //transfer main.Point to sting.Point
        int dataNumber = data.length;
        gridgrowing.Point[] points = new gridgrowing.Point[dataNumber];
        for (int i = 0; i < data.length; i++) {
            double xValue = data[i].vectors[0];
            double yValue = data[i].vectors[1];
            gridgrowing.Point point = new gridgrowing.Point(xValue, yValue);
            points[i] = point;
        }

        GridClustering gc = new GridClustering(points, mParameter, nxParameter, nyParameter);
        if (gc.dataGridImage()) {
            gc.findSeeds(optionParameter);
        }
        gc.seedGrowing();
        gc.assignClusterIDtoPoints();
        long duration = System.currentTimeMillis() - startTime;
        //gc.printJ();

        Cluster[] clusters = new Cluster[gc.clustersNumber];
        for (int i = 0; i < gc.clustersNumber; i++) {
            clusters[i] = new Cluster(rd.isGPSData, data[0].vectors.length);
        }
        for (int i = 0; i < gc.data.length; i++) {
            if (gc.data[i].clusterID > 0) {
                //System.out.println("clusterID: "+ gc.data[i].clusterID);
                double d[] = new double[2];
                d[0] = gc.data[i].xValue;
                d[1] = gc.data[i].yValue;
                main.Point point = new main.Point(d, rd.isGPSData);
                clusters[gc.data[i].clusterID - 1].pointsList.add(point);
            }
        }

        //clean empty clusters by AdamGu0
        ArrayList<Cluster> clusterList = new ArrayList<>();
        for (Cluster c : clusters) {
            if (c.pointsList.isEmpty()) continue;
            c.calcCentroid(new Point(rd.isGPSData));
            clusterList.add(c);
        }
        clusters = new Cluster[clusterList.size()];
        for (int i = 0; i < clusterList.size(); i++) {
            clusters[i] = clusterList.get(i);
        }
        
        showResultInfo(clusters, duration, "GridGrowing");
        showResult(clusters);

        //save the GridGrowing cluster point in json file, for drawing point on googlemap
        // saveCluster(preFileName+"_GridGrowing", clusters, clusters.length);
    }

    private void showResult(Cluster[] clusters) {
        resultClusters = clusters;
        clusterPanel.clusters = null;

        if (rd.isGPSData) {
            tabbedViewerPanel.setSelectedIndex(2);
            mapKit.setWaypoints(resultClusters);
            return;
        }

        if (rd.getVectorSize() != 2) {
            tabbedViewerPanel.setSelectedIndex(0);
        } else {
            tabbedViewerPanel.setSelectedIndex(1);
            clusterPanel.showCluster(resultClusters);
        }
    }

    private void showWarning(String text) {
        stateLabel.setText(text);
    }

    private boolean isGPSData;
    private ReadData rd;
    private Point[] data; // extracted data of points from file
    private String algorithm;
    private String fileName;
    private String exportFileName;
    private ClusterPanel clusterPanel;
    private MapKit mapKit;
    private Cluster[] resultClusters;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel algorithmLabel;
    private javax.swing.JLabel chLabel;
    private javax.swing.JLabel clustersLabel;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JLabel dataTypeLabel;
    private javax.swing.JButton dbscanButton;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JLabel dimensionsLabel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JTextField epsTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JMenuItem gpsDataMenuItem;
    private javax.swing.JButton gridBasedButton;
    private javax.swing.JPanel gridBasedPanel;
    private javax.swing.JButton gridGrowingButton;
    private javax.swing.JLabel gridSizeLabel;
    private javax.swing.JSlider gridSizeSlider;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField iterationsTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kMeansButton;
    private javax.swing.JTextField kMeansTextField;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JTextField mTextField;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField minPtsTextField;
    private javax.swing.JLabel mseLabel;
    private javax.swing.JMenuItem normalDataMenuItem;
    private javax.swing.JTextField nxTextField;
    private javax.swing.JTextField nyTextField;
    private javax.swing.JComboBox<String> optionComboBox;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JButton smartSwapButton;
    private javax.swing.JTextField smartSwapTextField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTabbedPane tabbedViewerPanel;
    private javax.swing.JLabel timeLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
